### ISSUE TITLE
[Add Check]: Check that if experimenters string does not have comma

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwbinspector#33]
If a user provides a comma-separated scalar string for `nwbfile.experimeter`, the inspector should recommend that they instead store an array of experimenter names. Same for keywords and related publications.

**Comment by bendichter** [comment]
This is a bit tricky for experimenters, because they might have listed the name Last, First

**Comment by CodyCBakerPhD** [comment]
The [BP section for experimenters](https://nwbinspector.readthedocs.io/en/dev/best_practices/nwbfile_metadata.html#experimenter) does not describe the format in which they ought to write these things down: should this be updated to some standard, such as 

Last Name, M. I., First Name 

M. I. - 'middle initial'

And how should multiple experimenters be handled?

**Comment by bendichter** [comment]
multiple experimenters should be handled as a vector of strings

**Comment by CodyCBakerPhD** [comment]
OK so, as I understand the heart of this original issue is to try to detect people encoding multiple experimenters with comma-separation instead of being added as different elements of the vector.

However, there are several different ways people can encode a single experimenter name, such as

(a) Firstname Lastname
(b) Lastname, Firstname
(c) [Optional]: Firstname, M.I., Lastname
(di) [Optional]: Lastname, Firstname, M.I.
(dii) [Optional]: Lastname, Firstname M.I.
(e) [Optional]: Lastname, M.I., Firstname

Now, we can still try to catch the heart of this issue by triggering the violation `if any((experimenter.count(",") for experimenter in nwbfile.experimenters)) > 3`

However, since the Best Practices make many references to trying to make NWBFiles machine-readable, I wonder if it might be in our best interest to encourage a single standard for encoding names (from a-e above), which would also make this kind of check easier and more reliable to catch.

Note: the [experimenter schema](https://nwb-schema.readthedocs.io/en/latest/format.html?highlight=experimenter#groups-general) also mentions that roles can be specified. I'd propose that a Best Practice for that could be optionally including `NameOfRole: ` before the name of the individual to make this easier to parse.

**Comment by bendichter** [comment]
Here's DANDI's regex for name: https://github.com/dandi/dandi-schema/blob/ffa49ef5dc84bc5a234fbc9ca9ba04b872539893/dandischema/models.py#L48

**Comment by CodyCBakerPhD** [comment]
> Here's DANDI's regex for name: https://github.com/dandi/dandi-schema/blob/ffa49ef5dc84bc5a234fbc9ca9ba04b872539893/dandischema/models.py#L48

Then their regex matches option (dii).

That could regex could be improved however; note that it allows numbers included in names (try `re.fullmatch(pattern=r"^([\w\s\-]+),\s+([\w\s\-\.]+)$", string="Baker2, Cody1")`) and disallows apostrophes (like`re.fullmatch(pattern=r"^([\w\s\-]+),\s+([\w\s\-\.]+)$", string="O'Baker, Cody")`).

Also note it does not accommodate role assignment of each experimenter, which the [NWB Schema](https://nwb-schema.readthedocs.io/en/latest/format.html?highlight=experimenter#groups-general) indicates is allowed

@bendichter So do you think we should make it a Best Practice to enforce structure (dii)? How should we deal with roles?

**Comment by bendichter** [comment]
@CodyCBakerPhD good points. Maybe we should raise these issues on the dandi schema repo

**Comment by CodyCBakerPhD** [comment]
Turns out that was an older version (not most recent master): https://github.com/dandi/dandi-schema/blob/master/dandischema/models.py#L60

And they may continue to think numbers in names are OK.

One thing to note though as I look through their code and how they use it, I'm not 100% sure they actually require the NWBAsset experimenter metadata to follow that, that's just what they enforce for their dandi assets after extraction. So whatever format the NWB team decides to support for this as a 'best practice' can always be mapped into what dandi expects via their intermediate metadata handling functions.

**Comment by bendichter** [comment]
@CodyCBakerPhD yes, exactly. This is a dandiset metadata requirement. I'd like to have the option of automatically pulling the experimenter metadata into the dandiset metadata, which is why I thought it might be convenient to have the same regex as a best practice.
