### ISSUE TITLE
why check unique vals <= 4?

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#6]
This line is cluttering up the inspect output: https://github.com/NeurodataWithoutBorders/nwbinspector/blob/7ceab6262a75e0699e824d7e2babd918c5fde739/nwbinspector.py#L111-L112

I get why we are detecting a single unique value or two because it could be a boolean, but should we print anything for 3 or 4 unique values? What is the thinking behind this?

**Comment by rly** [comment]
Let's remove that. There were some data files that had dataset values like "correct", "incorrect", and "early response", and it was nice to have those printed out since it had already calculated the unique values. This also identifies places where an eventual enum type would be useful for NWB. But for now, yeah, it's clutter.
